# Ejercicios Extraclase Avance 2
------------------------------------------------------------
### Estudiantes:

- #### Ana Melissa Vásquez Rojas 
- #### Daniel Duarte Cordero 

## Pregunta 1

Determina si una matriz cuadrada $A ∈ ℝ^{m×m}$  tiene una única factorización LU.

Basado en el teorema: Una matriz cuadrada A tiene una única factorización LU si y solo si 
todas sus submatrices principales $A_{1:k,1:k}$ son invertibles si y solo si
rango $(A_{1:k,1:k}) = k$ para todo $k = 1,...,m$

Parámetros:
- `A`: Matriz cuadrada $ m \times m $.

Retorna:

- `tf=1` si \( A \) tiene una única factorización LU.  
- `tf=0` si no la tiene.



In [53]:

import numpy as np

def tieneUnicaFactLU(A):

    A = np.array(A)
    m, n = A.shape

    # Verificar que A sea cuadrada
    if m != n:
        return 0

    # Verificación del rango de la matriz principal
    if np.linalg.matrix_rank(A) != m:
        return 0  # La matriz tiene rango diferente de m, entonces no hay LU única
    else:
        return 1  # Sí tiene una única factorización LU
    
# Caso 1: matriz con LU única
A1 = np.array([
    [2, 1, 1, 0, 0],
    [4, 3, 3, 1, 0],
    [8, 7, 9, 5, 1],
    [6, 7, 9, 8, 4],
    [2, 2, 3, 4, 7]
])

# Caso 2: matriz sin LU única (submatrices principales no invertibles)
A2 = np.array([
    [1, 2, 3, 4, 5],
    [2, 4, 6, 8, 10],
    [1, 1, 1, 1, 1],
    [3, 6, 9, 12, 15],
    [0, 0, 0, 0, 0]
])

print("A1 tiene LU única:", "tf=", tieneUnicaFactLU(A1))  # 1
print("A2 tiene LU única:", "tf=",tieneUnicaFactLU(A2))  # 0



A1 tiene LU única: tf= 1
A2 tiene LU única: tf= 0


## Pregunta 3

Implementa la factorización $QR$ de una matriz cuadrada $ A \in \mathbb{R}^{m \times m} $ utilizando el proceso de ortogonalización de Gram-Schmidt.

### Fundamento teórico

La factorización $ QR $ permite expresar cualquier matriz cuadrada $ A $ como el producto:

$A = QR$

- $ Q \in \mathbb{R}^{m \times m} $ es una matriz ortogonal, es decir, $ Q^T Q = Q Q^T= Im $,
- $ R \in \mathbb{R}^{m \times m} $ es una matriz triangular superior.

Esta descomposición se obtiene mediante el proceso de Gram-Schmidt:

$
\begin{align*}
u_1 &= a_1, \\
e_1 &= \frac{u_1}{\|u_1\|_2}, \\
u_k &= a_k - \sum_{j=1}^{k-1} \langle a_k, e_j \rangle e_j, \\
e_k &= \frac{u_k}{\|u_k\|_2}, \quad \text{para } k = 2, 3, ..., m.
\end{align*}
$

### Parámetros

- `A`: Matriz cuadrada $ m \times m $.

### Retorna

- `Q`: Matriz ortogonal $ Q $.
- `R`: Matriz triangular superior $ R $.


In [61]:
import numpy as np

def fact_qr(A):
    A = np.array(A, dtype=float)
    m, n = A.shape
    Q = np.zeros((m, n))  
    R = np.zeros((n, n))

    for k in range(n):
        ak = A[:, k]       # Paso 1: tomar columna ak
        uk = ak.copy()     # Inicializar uk como ak

        aux = np.zeros(m)
        for j in range(k):
            ej = Q[:, j]                        # Paso 2: ej 
            R[j, k] = ak @ ej                 # producto punto <ak, ek>
            aux += R[j, k] * ej                  # Sumatoria
        uk = ak - aux
        
        R[k, k] = np.linalg.norm(uk)            # Paso 3: ||uk||
        if R[k, k] == 0:
            raise ValueError("Columna linealmente dependiente detectada")

        ek = uk / R[k, k]                       # Paso 4: ek = uk / ||uk||
        Q[:, k] = ek

    return Q, R



    
A = A = [
    [  2, -1,  3,  0,  1, -2,  4, -3,  5,   6],
    [ -3,  5, -2,  1,  4, -6,  7, -8,  9,  10],
    [  1, -2,  4, -3,  5, -7,  8, -9, 10,  11],
    [  4, -3,  1,  2, -5,  6, -7,  8, -9,  10],
    [ -5,  7, -4,  6,  3, -1,  2, -8,  9, -10],
    [  6, -4,  5, -7,  8,  1, -3,  2, -9,  10],
    [ -7,  9, -6,  8, -10, 11,  3, -5,  4, -12],
    [  8, -6,  7, -9, 10, -12, 13,  5, -4,   3],
    [ -9, 11, -8, 10, -12, 14, -16, 17,  6,  -5],
    [ 10, -8,  9, -11, 12, -14, 15, -17, 18,  7]
]

Q, R = fact_qr(A)
print('Q=', Q)
print('R=', R)



Q= [[ 0.  0.  0.  1. -0. -0. -0.  0. -0. -1.]
 [-0.  0.  0. -0.  0. -0. -0. -0. -1.  0.]
 [ 0. -0.  1.  0. -0.  0. -0.  0.  0.  1.]
 [ 0.  0. -1.  1.  0. -0. -0. -0. -0.  0.]
 [-0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0. -0. -0. -0.  1. -0. -0. -0.  0.]
 [-0.  0.  0.  0. -0. -0.  1. -0.  0.  0.]
 [ 0.  0.  0. -0. -0. -0. -0.  1.  0.  0.]
 [-0.  0. -0.  0. -0.  0. -1.  0.  0.  0.]
 [ 1.  0.  0. -0. -0. -0. -0. -1.  0. -0.]]
R= [[ 20. -19.  17. -20.  20. -20.  16.  -8.  -4.  19.]
 [  0.   6.  -0.   1.   3.   0.   5.  -2.  10.   1.]
 [  0.   0.   4.  -5.  10. -13.  16. -17.  18.   6.]
 [  0.   0.   0.   6.  -7.   6.  -4.   2.   1.   4.]
 [  0.   0.   0.   0.   9.  -9.   5. -10.   3.  -1.]
 [  0.   0.   0.   0.   0.   9. -12.   6. -11.   2.]
 [  0.   0.   0.   0.   0.   0.  11. -14.  -2.  -9.]
 [  0.   0.   0.   0.   0.   0.   0.  15. -14.  -4.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   7. -15.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   8.]]


## Pregunta 4

Implementa el método iterativo de **Gauss-Seidel** para resolver sistemas de ecuaciones lineales de la forma:

$$
Ax = b
$$
### Parámetros

- `A`: Matriz de coeficientes $ A \in \mathbb{R}^{m \times m} $.
- `b`: Vector del lado derecho $ b \in \mathbb{R}^{m} $.
- `x0`: Vector inicial $ x^{(0)} \in \mathbb{R}^{m} $.
- `tol`: Tolerancia para el criterio de convergencia.
- `max_iter`: Número máximo de iteraciones.

### Sistema a resolver

Se debe resolver el sistema $Ax = b$, donde:

- $A \in \mathbb{R}^{1000 \times 1000}$, tal que:

$$
A[i,j] =
\begin{cases}
1001 & \text{si } i = j \\
1 & \text{si } i \ne j
\end{cases}
$$

- $b \in \mathbb{R}^{1000}$ es el vector columna:

$$
b = (1, 1, \dots, 1)^T
$$

### Retorna

- Vector $x \in \mathbb{R}^{m}$ que representa la solución aproximada al sistema $Ax = b$.




In [69]:
import numpy as np

def sust_adelante(A,b):
    m=len(b)
    x=np.zeros(m)
    for i in range (m):
        aux=0
        for j in range(i):# solo hasta i-1
            aux+= A[i,j]*x[j]
        x[i]=(b[i]-aux)/A[i,i]
    return x


def gauss_seidel(A, b, xk, tol=1e-6, max_iter=100):
    m = A.shape[0]

    # Descomposición L + D y U
    L = np.tril(A, -1)
    D = np.diag(np.diag(A))
    U = np.triu(A, 1)
    LD = L + D

    for k in range(1, max_iter + 1):
        # Fórmula teórica del método G-S hacia adelante:
        # x(k+1) =  - (L + D)^(-1) · U · x(k) + (L + D)^(-1) · b
        # Se reescribe como:
        # x(k+1) = (L + D)^(-1) · (b - U · x(k))
        # Como no podemos usar la inversa directamente,
        # reescribimos el sistema: (L + D) · x(k+1) = b - U · x(k)
        # y lo resolvemos por sustitución hacia adelante.
        
        z = b - U @ xk
        x_new = sust_adelante(LD, z)
        error = np.linalg.norm(A @ x_new - b)

        if error < tol:
            return x_new, k, error
        xk = x_new
    return xk, k, error


# Tamaño
m = 1000

# Matriz A: 1001 en la diagonal, 1 fuera de ella
A = np.ones((m, m))
np.fill_diagonal(A, 1001)

# Vector b: todos unos
b = np.ones(m)

# Vector inicial
x0 = np.zeros(m)

# Ejecutar
raiz, iteraciones, error = gauss_seidel(A, b, x0, tol=1e-6, max_iter=100)
print("Error final:", error)
    

Error final: 3.578478217410359e-07
